export const countryList = [
	{ address_text: 'Afghanistan', address_id: 'AFG' },
	{ address_text: 'Åland Islands', address_id: 'ALA' },
	{ address_text: 'Albania', address_id: 'ALB' },
	{ address_text: 'Algeria', address_id: 'DZA' },
	{ address_text: 'Andorra', address_id: 'AND' },
	{ address_text: 'Angola', address_id: 'AGO' },
	{ address_text: 'Anguilla', address_id: 'AIA' },
	{ address_text: 'Antarctica', address_id: 'ATA' },
	{ address_text: 'Antigua and Barbuda', address_id: 'ATG' },
	{ address_text: 'Argentina', address_id: 'ARG' },
	{ address_text: 'Armenia', address_id: 'ARM' },
	{ address_text: 'Aruba', address_id: 'ABW' },
	{ address_text: 'Australia', address_id: 'AUS' },
	{ address_text: 'Austria', address_id: 'AUT' },
	{ address_text: 'Azerbaijan', address_id: 'AZE' },
	{ address_text: 'Bahamas', address_id: 'BHS' },
	{ address_text: 'Bahrain', address_id: 'BHR' },
	{ address_text: 'Bangladesh', address_id: 'BGD' },
	{ address_text: 'Barbados', address_id: 'BRB' },
	{ address_text: 'Belarus', address_id: 'BLR' },
	{ address_text: 'Belgium', address_id: 'BEL' },
	{ address_text: 'Belize', address_id: 'BLZ' },
	{ address_text: 'Benin', address_id: 'BEN' },
	{ address_text: 'Bermuda', address_id: 'BMU' },
	{ address_text: 'Bhutan', address_id: 'BTN' },
	{ address_text: 'Bolivia', address_id: 'BOL' },
	{ address_text: 'Bonaire', address_id: 'BES' },
	{ address_text: 'Bosnia and Herzegovina', address_id: 'BIH' },
	{ address_text: 'Botswana', address_id: 'BWA' },
	{ address_text: 'Bouvet Island', address_id: 'BVT' },
	{ address_text: 'Brazil', address_id: 'BRA' },
	{ address_text: 'British Indian Ocean Territory', address_id: 'IOT' },
	{ address_text: 'Brunei Darussalam', address_id: 'BRN' },
	{ address_text: 'Bulgaria', address_id: 'BGR' },
	{ address_text: 'Burkina Faso', address_id: 'BFA' },
	{ address_text: 'Burundi', address_id: 'BDI' },
	{ address_text: 'Cambodia', address_id: 'KHM' },
	{ address_text: 'Cameroon', address_id: 'CMR' },
	{ address_text: 'Canada', address_id: 'CAN' },
	{ address_text: 'Cape Verde', address_id: 'CPV' },
	{ address_text: 'Cayman Islands', address_id: 'CYM' },
	{ address_text: 'Central African Republic', address_id: 'CAF' },
	{ address_text: 'Chad', address_id: 'TCD' },
	{ address_text: 'Chile', address_id: 'CHL' },
	{ address_text: 'China', address_id: 'CHN' },
	{ address_text: 'Christmas Island', address_id: 'CXR' },
	{ address_text: 'Cocos (Keeling) Islands', address_id: 'CCK' },
	{ address_text: 'Colombia', address_id: 'COL' },
	{ address_text: 'Comoros', address_id: 'COM' },
	{ address_text: 'Congo', address_id: 'COG' },
	{ address_text: 'Congo, The Democratic Republic of the', address_id: 'COD' },
	{ address_text: 'Cook Islands', address_id: 'COK' },
	{ address_text: 'Costa Rica', address_id: 'CRI' },
	{ address_text: 'Croatia', address_id: 'HRV' },
	{ address_text: 'Cuba', address_id: 'CUB' },
	{ address_text: 'Curaçao', address_id: 'CUW' },
	{ address_text: 'Cyprus', address_id: 'CYP' },
	{ address_text: 'Czech Republic', address_id: 'CZE' },
	{ address_text: 'Côte d’Ivoire', address_id: 'CIV' },
	{ address_text: 'Denmark', address_id: 'DNK' },
	{ address_text: 'Djibouti', address_id: 'DJI' },
	{ address_text: 'Dominica', address_id: 'DMA' },
	{ address_text: 'Dominican Republic', address_id: 'DOM' },
	{ address_text: 'Ecuador', address_id: 'ECU' },
	{ address_text: 'Egypt', address_id: 'EGY' },
	{ address_text: 'El Salvador', address_id: 'SLV' },
	{ address_text: 'Equatorial Guinea', address_id: 'GNQ' },
	{ address_text: 'Eritrea', address_id: 'ERI' },
	{ address_text: 'Estonia', address_id: 'EST' },
	{ address_text: 'Eswatini', address_id: 'SWZ' },
	{ address_text: 'Ethiopia', address_id: 'ETH' },
	{ address_text: 'Falkland Islands (Malvinas)', address_id: 'FLK' },
	{ address_text: 'Faroe Islands', address_id: 'FRO' },
	{ address_text: 'Fiji', address_id: 'FJI' },
	{ address_text: 'Finland', address_id: 'FIN' },
	{ address_text: 'France', address_id: 'FRA' },
	{ address_text: 'French Guiana', address_id: 'GUF' },
	{ address_text: 'French Polynesia', address_id: 'PYF' },
	{ address_text: 'French Southern Territories', address_id: 'ATF' },
	{ address_text: 'Gabon', address_id: 'GAB' },
	{ address_text: 'Gambia', address_id: 'GMB' },
	{ address_text: 'Georgia', address_id: 'GEO' },
	{ address_text: 'Germany', address_id: 'DEU' },
	{ address_text: 'Ghana', address_id: 'GHA' },
	{ address_text: 'Gibraltar', address_id: 'GIB' },
	{ address_text: 'Greece', address_id: 'GRC' },
	{ address_text: 'Greenland', address_id: 'GRL' },
	{ address_text: 'Grenada', address_id: 'GRD' },
	{ address_text: 'Guadeloupe', address_id: 'GLP' },
	{ address_text: 'Guatemala', address_id: 'GTM' },
	{ address_text: 'Guernsey', address_id: 'GGY' },
	{ address_text: 'Guinea', address_id: 'GIN' },
	{ address_text: 'Guinea-Bissau', address_id: 'GNB' },
	{ address_text: 'Guyana', address_id: 'GUY' },
	{ address_text: 'Haiti', address_id: 'HTI' },
	{ address_text: 'Heard Island and McDonald Islands', address_id: 'HMD' },
	{ address_text: 'Holy See (Vatican City State)', address_id: 'VAT' },
	{ address_text: 'Honduras', address_id: 'HND' },
	{ address_text: 'Hong Kong', address_id: 'HKG' },
	{ address_text: 'Hungary', address_id: 'HUN' },
	{ address_text: 'Iceland', address_id: 'ISL' },
	{ address_text: 'India', address_id: 'IND' },
	{ address_text: 'Indonesia', address_id: 'IDN' },
	{ address_text: 'Iran, Islamic Republic of', address_id: 'IRN' },
	{ address_text: 'Iraq', address_id: 'IRQ' },
	{ address_text: 'Ireland', address_id: 'IRL' },
	{ address_text: 'Isle of Man', address_id: 'IMN' },
	{ address_text: 'Israel', address_id: 'ISR' },
	{ address_text: 'Italy', address_id: 'ITA' },
	{ address_text: 'Jamaica', address_id: 'JAM' },
	{ address_text: 'Japan', address_id: 'JPN' },
	{ address_text: 'Jersey', address_id: 'JEY' },
	{ address_text: 'Jordan', address_id: 'JOR' },
	{ address_text: 'Kazakhstan', address_id: 'KAZ' },
	{ address_text: 'Kenya', address_id: 'KEN' },
	{ address_text: 'Kiribati', address_id: 'KIR' },
	{ address_text: 'Korea, Democratic People’s Republic of', address_id: 'PRK' },
	{ address_text: 'Korea, Republic of', address_id: 'KOR' },
	{ address_text: 'Kosovo', address_id: 'XKV' },
	{ address_text: 'Kuwait', address_id: 'KWT' },
	{ address_text: 'Kyrgyzstan', address_id: 'KGZ' },
	{ address_text: 'Lao People’s Democratic Republic', address_id: 'LAO' },
	{ address_text: 'Latvia', address_id: 'LVA' },
	{ address_text: 'Lebanon', address_id: 'LBN' },
	{ address_text: 'Lesotho', address_id: 'LSO' },
	{ address_text: 'Liberia', address_id: 'LBR' },
	{ address_text: 'Libya', address_id: 'LBY' },
	{ address_text: 'Liechtenstein', address_id: 'LIE' },
	{ address_text: 'Lithuania', address_id: 'LTU' },
	{ address_text: 'Luxembourg', address_id: 'LUX' },
	{ address_text: 'Macao', address_id: 'MAC' },
	{ address_text: 'North Macedonia', address_id: 'MKD' },
	{ address_text: 'Madagascar', address_id: 'MDG' },
	{ address_text: 'Malawi', address_id: 'MWI' },
	{ address_text: 'Malaysia', address_id: 'MYS' },
	{ address_text: 'Maldives', address_id: 'MDV' },
	{ address_text: 'Mali', address_id: 'MLI' },
	{ address_text: 'Malta', address_id: 'MLT' },
	{ address_text: 'Martinique', address_id: 'MTQ' },
	{ address_text: 'Mauritania', address_id: 'MRT' },
	{ address_text: 'Mauritius', address_id: 'MUS' },
	{ address_text: 'Mayotte', address_id: 'MYT' },
	{ address_text: 'Mexico', address_id: 'MEX' },
	{ address_text: 'Moldova, Republic of', address_id: 'MDA' },
	{ address_text: 'Monaco', address_id: 'MCO' },
	{ address_text: 'Mongolia', address_id: 'MNG' },
	{ address_text: 'Montenegro', address_id: 'MNE' },
	{ address_text: 'Montserrat', address_id: 'MSR' },
	{ address_text: 'Morocco', address_id: 'MAR' },
	{ address_text: 'Mozambique', address_id: 'MOZ' },
	{ address_text: 'Myanmar', address_id: 'MMR' },
	{ address_text: 'Namibia', address_id: 'NAM' },
	{ address_text: 'Nauru', address_id: 'NRU' },
	{ address_text: 'Nepal', address_id: 'NPL' },
	{ address_text: 'Netherlands', address_id: 'NLD' },
	{ address_text: 'New Caledonia', address_id: 'NCL' },
	{ address_text: 'New Zealand', address_id: 'NZL' },
	{ address_text: 'Nicaragua', address_id: 'NIC' },
	{ address_text: 'Niger', address_id: 'NER' },
	{ address_text: 'Nigeria', address_id: 'NGA' },
	{ address_text: 'Niue', address_id: 'NIU' },
	{ address_text: 'Norfolk Island', address_id: 'NFK' },
	{ address_text: 'Norway', address_id: 'NOR' },
	{ address_text: 'Oman', address_id: 'OMN' },
	{ address_text: 'Pakistan', address_id: 'PAK' },
	{ address_text: 'Palestine, State of', address_id: 'PSE' },
	{ address_text: 'Panama', address_id: 'PAN' },
	{ address_text: 'Papua New Guinea', address_id: 'PNG' },
	{ address_text: 'Paraguay', address_id: 'PRY' },
	{ address_text: 'Peru', address_id: 'PER' },
	{ address_text: 'Philippines', address_id: 'PHL' },
	{ address_text: 'Pitcairn', address_id: 'PCN' },
	{ address_text: 'Poland', address_id: 'POL' },
	{ address_text: 'Portugal', address_id: 'PRT' },
	{ address_text: 'Puerto Rico', address_id: 'PRI' },
	{ address_text: 'Qatar', address_id: 'QAT' },
	{ address_text: 'Republic of South Sudan', address_id: 'SSD' },
	{ address_text: 'Romania', address_id: 'ROU' },
	{ address_text: 'Russian Federation', address_id: 'RUS' },
	{ address_text: 'Rwanda', address_id: 'RWA' },
	{ address_text: 'Réunion', address_id: 'REU' },
	{ address_text: 'Saint Barthélemy', address_id: 'BLM' },
	{ address_text: 'Saint Helena, Ascension and Tristan da Cunha', address_id: 'SHN' },
	{ address_text: 'Saint Kitts and Nevis', address_id: 'KNA' },
	{ address_text: 'Saint Lucia', address_id: 'LCA' },
	{ address_text: 'Saint Martin (French Part)', address_id: 'MAF' },
	{ address_text: 'Saint Pierre and Miquelon', address_id: 'SPM' },
	{ address_text: 'Saint Vincent and the Grenadines', address_id: 'VCT' },
	{ address_text: 'Samoa', address_id: 'WSM' },
	{ address_text: 'San Marino', address_id: 'SMR' },
	{ address_text: 'Sao Tome and Principe', address_id: 'STP' },
	{ address_text: 'Saudi Arabia', address_id: 'SAU' },
	{ address_text: 'Senegal', address_id: 'SEN' },
	{ address_text: 'Serbia', address_id: 'SRB' },
	{ address_text: 'Seychelles', address_id: 'SYC' },
	{ address_text: 'Sierra Leone', address_id: 'SLE' },
	{ address_text: 'Singapore', address_id: 'SGP' },
	{ address_text: 'Sint Maarten', address_id: 'SXM' },
	{ address_text: 'Slovakia', address_id: 'SVK' },
	{ address_text: 'Slovenia', address_id: 'SVN' },
	{ address_text: 'Solomon Islands', address_id: 'SLB' },
	{ address_text: 'Somalia', address_id: 'SOM' },
	{ address_text: 'South Africa', address_id: 'ZAF' },
	{ address_text: 'South Georgia and the South Sandwich Islands', address_id: 'SGS' },
	{ address_text: 'Spain', address_id: 'ESP' },
	{ address_text: 'Sri Lanka', address_id: 'LKA' },
	{ address_text: 'Sudan', address_id: 'SDN' },
	{ address_text: 'Suriname', address_id: 'SUR' },
	{ address_text: 'Svalbard and Jan Mayen', address_id: 'SJM' },
	{ address_text: 'Sweden', address_id: 'SWE' },
	{ address_text: 'Switzerland', address_id: 'CHE' },
	{ address_text: 'Syrian Arab Republic', address_id: 'SYR' },
	{ address_text: 'Taiwan, Province of China', address_id: 'TWN' },
	{ address_text: 'Tajikistan', address_id: 'TJK' },
	{ address_text: 'Tanzania, United Republic of', address_id: 'TZA' },
	{ address_text: 'Thailand', address_id: 'THA' },
	{ address_text: 'Timor-Leste', address_id: 'TLS' },
	{ address_text: 'Togo', address_id: 'TGO' },
	{ address_text: 'Tokelau', address_id: 'TKL' },
	{ address_text: 'Tonga', address_id: 'TON' },
	{ address_text: 'Trinidad and Tobago', address_id: 'TTO' },
	{ address_text: 'Tunisia', address_id: 'TUN' },
	{ address_text: 'Turkey', address_id: 'TUR' },
	{ address_text: 'Turkmenistan', address_id: 'TKM' },
	{ address_text: 'Turks and Caicos Islands', address_id: 'TCA' },
	{ address_text: 'Tuvalu', address_id: 'TUV' },
	{ address_text: 'Uganda', address_id: 'UGA' },
	{ address_text: 'Ukraine', address_id: 'UKR' },
	{ address_text: 'United Arab Emirates', address_id: 'ARE' },
	{ address_text: 'United Kingdom', address_id: 'GBR' },
	{ address_text: 'United States', address_id: 'USA' },
	{ address_text: 'United States Minor Outlying Islands', address_id: 'UMI' },
	{ address_text: 'Uruguay', address_id: 'URY' },
	{ address_text: 'Uzbekistan', address_id: 'UZB' },
	{ address_text: 'Vanuatu', address_id: 'VUT' },
	{ address_text: 'Venezuela, Bolivarian Republic of', address_id: 'VEN' },
	{ address_text: 'Viet Nam', address_id: 'VNM' },
	{ address_text: 'Virgin Islands British', address_id: 'VGB' },
	{ address_text: 'Wallis and Futuna', address_id: 'WLF' },
	{ address_text: 'Western Sahara', address_id: 'ESH' },
	{ address_text: 'Yemen', address_id: 'YEM' },
	{ address_text: 'Zambia', address_id: 'ZMB' },
	{ address_text: 'Zimbabwe', address_id: 'ZWE' },
];